sudo: required

services:
 - docker

language: bash

env:
  matrix:
  - DOCKER_ARCH=amd64
  - DOCKER_ARCH=arm64
 #- DOCKER_ARCH=arm <- cannot get ca-certificates to setup on qemu

script:
- ./build/travis_build.sh

jobs:
  include:

  - stage: Manifest
    script:
    - ./build/travis_manifest.sh
    env:
