apiVersion: v1
kind: List
items:
- kind: ServiceAccount
  apiVersion: v1
  metadata:
    name: glusterfs
- kind: SecurityContextConstraints
  apiVersion: v1
  metadata: 
    name: glusterfs
    labels: 
      name: glusterfs
  allowPrivilegedContainer: true
  allowHostDirVolumePlugin: true
  allowedCapabilities:
  - SYS_ADMIN
  runAsUser: 
    type: RunAsAny
  seLinuxContext: 
    type: RunAsAny
  users: 
  - system:serviceaccounts:default:glusterfs
  groups: 
  - system:cluster-admins
- kind: Service
  apiVersion: v1
  metadata:
    name: storage-webhosting
  spec:
    PortalIP: None
    ClusterIP: None
    ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: glusterfs-api
      port: 24007
      targetPort: 24007
    - name: glusterfs-infiniband
      port: 24008
      targetPort: 24008
    - name: glusterfs-brick0
      port: 49152
      targetPort: 49152
    - name: glusterfs-nfs-0
      port: 38465
      targetPort: 38465
    - name: glusterfs-nfs-1
      port: 38466
      targetPort: 38466
    - name: glusterfs-nfs-2
      port: 38467
      targetPort: 38467
    - name: nfs-rpc
      port: 111
      targetPort: 111
    - name: nfs-rpc-udp
      port: 111
      targetPort: 111
      protocol: UDP
    - name: nfs-portmap
      port: 2049
      targetPort: 2049
    selector:
      service: storage-webhosting
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: storage-webhosting1
  status:
    latestVersion: 1
  spec:
    replicas: 1
    selector:
      deploymentconfig: storage-webhosting1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          service: storage-webhosting
          deploymentconfig: storage-webhosting1
      spec:
        serviceAccount: glusterfs
        dnsPolicy: ClusterFirst
        containers:
        - name: glusterfs-server1
          image: hoolia/kubernetes-glusterfs-server:latest
          ports:
          - containerPort: 22
          - containerPort: 24007
          - containerPort: 24008
          - containerPort: 49152
          - containerPort: 38465
          - containerPort: 38466
          - containerPort: 38467
          - containerPort: 2049
          - containerPort: 111
          - containerPort: 111
            protocol: UDP
          env:
          - name: MAX_VOLUMES
            value: "100"
          - name: GLUSTER_VOL
            value: shared
          - name: GLUSTER_BRICK_PATH
            value: /gluster_volume
          - name: SERVICE_NAME
            value: storage-webhosting.default.svc.cluster.local
          - name: ROOT_PASSWORD
            value: container_root_password
          - name: DEBUG
            value: "1"
          - name: SSH_PORT
            value: "22"
          volumeMounts:
          - name: shared-webhosting1
            mountPath: /gluster_volume
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add:
              - SYS_ADMIN
        volumes:
          - name: shared-webhosting1
            hostPath:
              path: "/mnt/shared/webhosting/node1"
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - glusterfs-server1
        from:
          kind: ImageStreamTag
          name: kubernetes-glusterfs-server:latest
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: storage-webhosting2
  status:
    latestVersion: 1
  spec:
    replicas: 1
    selector:
      deploymentconfig: storage-webhosting2
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          service: storage-webhosting
          deploymentconfig: storage-webhosting2
      spec:
        serviceAccount: glusterfs
        dnsPolicy: ClusterFirst
        containers:
        - name: glusterfs-server2
          image: hoolia/kubernetes-glusterfs-server:latest
          ports:
          - containerPort: 22
          - containerPort: 24007
          - containerPort: 24008
          - containerPort: 49152
          - containerPort: 38465
          - containerPort: 38466
          - containerPort: 38467
          - containerPort: 2049
          - containerPort: 111
          - containerPort: 111
            protocol: UDP
          env:
          - name: MAX_VOLUMES
            value: "100"
          - name: GLUSTER_VOL
            value: shared
          - name: GLUSTER_BRICK_PATH
            value: /gluster_volume
          - name: SERVICE_NAME
            value: storage-webhosting.default.svc.cluster.local
          - name: ROOT_PASSWORD
            value: container_root_password
          - name: DEBUG
            value: "1"
          - name: SSH_PORT
            value: "22"
          volumeMounts:
          - name: shared-webhosting2
            mountPath: /gluster_volume
          securityContext:
            privileged: true
            runAsUser: 0
            capabilities:
              add:
              - SYS_ADMIN
        volumes:
          - name: shared-webhosting2
            hostPath:
              path: "/mnt/shared/webhosting/node2"
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
        - glusterfs-server2
        from:
          kind: ImageStreamTag
          name: kubernetes-glusterfs-server:latest
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: kubernetes-glusterfs-server
  spec:
    dockerImageRepository: hoolia/kubernetes-glusterfs-server
- apiVersion: "v1"
  kind: "PersistentVolume"
  metadata:
    name: "shared-webhosting1"
  spec:
    capacity:
      storage: "1600Gi" 
    accessModes:
      - "ReadWriteMany"
    glusterfs: 
      endpoints: "shared-webhosting" 
      path: "shared1" 
      readOnly: false
    persistentVolumeReclaimPolicy: "Recycle"
